# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledYLTHfq.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSplitter,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1625, 560)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 0, 711, 31))
        self.textBrowser.setStyleSheet(u"background-color: rgb(170, 255, 255);")
        self.upload_tab = QTabWidget(self.centralwidget)
        self.upload_tab.setObjectName(u"upload_tab")
        self.upload_tab.setGeometry(QRect(0, 0, 1711, 461))
        self.upload_tab.setFocusPolicy(Qt.TabFocus)
        self.upload_tab.setTabShape(QTabWidget.Rounded)
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.upload_tab.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.upload_tab.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.scrollArea_3 = QScrollArea(self.tab_9)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(240, -10, 2671, 561))
        self.scrollArea_3.setFrameShape(QFrame.Box)
        self.scrollArea_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 2650, 540))
        self.label_46 = QLabel(self.scrollAreaWidgetContents_3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(1420, 0, 49, 16))
        self.splitter_17 = QSplitter(self.scrollAreaWidgetContents_3)
        self.splitter_17.setObjectName(u"splitter_17")
        self.splitter_17.setGeometry(QRect(30, 0, 201, 24))
        self.splitter_17.setOrientation(Qt.Horizontal)
        self.label_25 = QLabel(self.splitter_17)
        self.label_25.setObjectName(u"label_25")
        self.splitter_17.addWidget(self.label_25)
        self.pushButton_8 = QPushButton(self.splitter_17)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_17.addWidget(self.pushButton_8)
        self.lineEdit_18 = QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(1440, 30, 64, 22))
        self.scrollArea_4 = QScrollArea(self.scrollAreaWidgetContents_3)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(680, 30, 361, 261))
        self.scrollArea_4.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 342, 242))
        self.label_26 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(170, 20, 18, 16))
        self.label_27 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(170, 80, 29, 16))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_28 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(170, 110, 29, 21))
        self.label_29 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(30, 140, 101, 16))
        self.textBrowser_6 = QTextBrowser(self.scrollAreaWidgetContents_4)
        self.textBrowser_6.setObjectName(u"textBrowser_6")
        self.textBrowser_6.setGeometry(QRect(30, 160, 291, 51))
        self.label_30 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 100, 28, 16))
        self.label_31 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 70, 16, 16))
        self.lineEdit_10 = QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(60, 40, 81, 21))
        self.label_32 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 40, 21, 16))
        self.label_33 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(20, 10, 16, 16))
        self.splitter_18 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_18.setObjectName(u"splitter_18")
        self.splitter_18.setGeometry(QRect(60, 100, 61, 21))
        self.splitter_18.setOrientation(Qt.Horizontal)
        self.lineEdit_11 = QLineEdit(self.splitter_18)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.splitter_18.addWidget(self.lineEdit_11)
        self.label_34 = QLabel(self.splitter_18)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setFrameShape(QFrame.Panel)
        self.label_34.setFrameShadow(QFrame.Raised)
        self.splitter_18.addWidget(self.label_34)
        self.splitter_19 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_19.setObjectName(u"splitter_19")
        self.splitter_19.setGeometry(QRect(60, 70, 91, 21))
        self.splitter_19.setOrientation(Qt.Horizontal)
        self.lineEdit_12 = QLineEdit(self.splitter_19)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.splitter_19.addWidget(self.lineEdit_12)
        self.label_35 = QLabel(self.splitter_19)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setFrameShape(QFrame.Panel)
        self.label_35.setFrameShadow(QFrame.Raised)
        self.splitter_19.addWidget(self.label_35)
        self.splitter_20 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_20.setObjectName(u"splitter_20")
        self.splitter_20.setGeometry(QRect(60, 10, 81, 21))
        self.splitter_20.setOrientation(Qt.Horizontal)
        self.lineEdit_13 = QLineEdit(self.splitter_20)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.splitter_20.addWidget(self.lineEdit_13)
        self.label_36 = QLabel(self.splitter_20)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setFrameShape(QFrame.Panel)
        self.label_36.setFrameShadow(QFrame.Raised)
        self.splitter_20.addWidget(self.label_36)
        self.label_37 = QLabel(self.scrollAreaWidgetContents_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(170, 50, 29, 16))
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.splitter_21 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_21.setObjectName(u"splitter_21")
        self.splitter_21.setGeometry(QRect(200, 20, 91, 22))
        self.splitter_21.setOrientation(Qt.Horizontal)
        self.lineEdit_14 = QLineEdit(self.splitter_21)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.splitter_21.addWidget(self.lineEdit_14)
        self.label_38 = QLabel(self.splitter_21)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setFrameShape(QFrame.Panel)
        self.label_38.setFrameShadow(QFrame.Raised)
        self.splitter_21.addWidget(self.label_38)
        self.splitter_22 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_22.setObjectName(u"splitter_22")
        self.splitter_22.setGeometry(QRect(200, 50, 111, 22))
        self.splitter_22.setOrientation(Qt.Horizontal)
        self.lineEdit_15 = QLineEdit(self.splitter_22)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.splitter_22.addWidget(self.lineEdit_15)
        self.label_39 = QLabel(self.splitter_22)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setFrameShape(QFrame.Panel)
        self.label_39.setFrameShadow(QFrame.Raised)
        self.splitter_22.addWidget(self.label_39)
        self.splitter_23 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_23.setObjectName(u"splitter_23")
        self.splitter_23.setGeometry(QRect(201, 80, 101, 22))
        self.splitter_23.setOrientation(Qt.Horizontal)
        self.lineEdit_16 = QLineEdit(self.splitter_23)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.splitter_23.addWidget(self.lineEdit_16)
        self.label_40 = QLabel(self.splitter_23)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setFrameShape(QFrame.Panel)
        self.label_40.setFrameShadow(QFrame.Raised)
        self.splitter_23.addWidget(self.label_40)
        self.splitter_24 = QSplitter(self.scrollAreaWidgetContents_4)
        self.splitter_24.setObjectName(u"splitter_24")
        self.splitter_24.setGeometry(QRect(200, 110, 111, 21))
        self.splitter_24.setOrientation(Qt.Horizontal)
        self.lineEdit_17 = QLineEdit(self.splitter_24)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.splitter_24.addWidget(self.lineEdit_17)
        self.label_41 = QLabel(self.splitter_24)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setFrameShape(QFrame.Panel)
        self.label_41.setFrameShadow(QFrame.Raised)
        self.splitter_24.addWidget(self.label_41)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.splitter_32 = QSplitter(self.scrollAreaWidgetContents_3)
        self.splitter_32.setObjectName(u"splitter_32")
        self.splitter_32.setGeometry(QRect(690, 0, 191, 24))
        self.splitter_32.setOrientation(Qt.Horizontal)
        self.label_48 = QLabel(self.splitter_32)
        self.label_48.setObjectName(u"label_48")
        self.splitter_32.addWidget(self.label_48)
        self.pushButton_14 = QPushButton(self.splitter_32)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_32.addWidget(self.pushButton_14)
        self.tableComplaints = QTableWidget(self.scrollAreaWidgetContents_3)
        if (self.tableComplaints.columnCount() < 6):
            self.tableComplaints.setColumnCount(6)
        if (self.tableComplaints.rowCount() < 2):
            self.tableComplaints.setRowCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableComplaints.setItem(0, 0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableComplaints.setItem(0, 1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableComplaints.setItem(0, 2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableComplaints.setItem(0, 3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableComplaints.setItem(0, 4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableComplaints.setItem(0, 5, __qtablewidgetitem5)
        self.tableComplaints.setObjectName(u"tableComplaints")
        self.tableComplaints.setGeometry(QRect(0, 30, 631, 161))
        self.tableComplaints.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.tableComplaints.setLineWidth(2)
        self.tableComplaints.setMidLineWidth(1)
        self.tableComplaints.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableComplaints.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableComplaints.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableComplaints.setRowCount(2)
        self.tableComplaints.setColumnCount(6)
        self.tableComplaints.horizontalHeader().setVisible(False)
        self.tableComplaints.horizontalHeader().setMinimumSectionSize(4)
        self.tableComplaints.horizontalHeader().setDefaultSectionSize(100)
        self.tableComplaints.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableComplaints.horizontalHeader().setStretchLastSection(True)
        self.tableComplaints.verticalHeader().setVisible(False)
        self.tableComplaints.verticalHeader().setCascadingSectionResizes(True)
        self.tableComplaints.verticalHeader().setProperty("showSortIndicator", True)
        self.tableComplaints.verticalHeader().setStretchLastSection(False)
        self.splitter_25 = QSplitter(self.scrollAreaWidgetContents_3)
        self.splitter_25.setObjectName(u"splitter_25")
        self.splitter_25.setGeometry(QRect(1120, 0, 191, 24))
        self.splitter_25.setOrientation(Qt.Horizontal)
        self.label_42 = QLabel(self.splitter_25)
        self.label_42.setObjectName(u"label_42")
        self.splitter_25.addWidget(self.label_42)
        self.pushButton_9 = QPushButton(self.splitter_25)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_25.addWidget(self.pushButton_9)
        self.scrollArea_5 = QScrollArea(self.scrollAreaWidgetContents_3)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setGeometry(QRect(1120, 30, 211, 261))
        self.scrollArea_5.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_5.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_5.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 192, 242))
        self.splitter_26 = QSplitter(self.scrollAreaWidgetContents_5)
        self.splitter_26.setObjectName(u"splitter_26")
        self.splitter_26.setGeometry(QRect(20, 90, 161, 71))
        self.splitter_26.setOrientation(Qt.Vertical)
        self.splitter_27 = QSplitter(self.splitter_26)
        self.splitter_27.setObjectName(u"splitter_27")
        self.splitter_27.setOrientation(Qt.Horizontal)
        self.label_43 = QLabel(self.splitter_27)
        self.label_43.setObjectName(u"label_43")
        self.splitter_27.addWidget(self.label_43)
        self.pushButton_10 = QPushButton(self.splitter_27)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_27.addWidget(self.pushButton_10)
        self.splitter_26.addWidget(self.splitter_27)
        self.textBrowser_7 = QTextBrowser(self.splitter_26)
        self.textBrowser_7.setObjectName(u"textBrowser_7")
        self.splitter_26.addWidget(self.textBrowser_7)
        self.splitter_28 = QSplitter(self.scrollAreaWidgetContents_5)
        self.splitter_28.setObjectName(u"splitter_28")
        self.splitter_28.setGeometry(QRect(20, 170, 161, 71))
        self.splitter_28.setOrientation(Qt.Vertical)
        self.splitter_29 = QSplitter(self.splitter_28)
        self.splitter_29.setObjectName(u"splitter_29")
        self.splitter_29.setOrientation(Qt.Horizontal)
        self.label_44 = QLabel(self.splitter_29)
        self.label_44.setObjectName(u"label_44")
        self.splitter_29.addWidget(self.label_44)
        self.pushButton_11 = QPushButton(self.splitter_29)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_29.addWidget(self.pushButton_11)
        self.splitter_28.addWidget(self.splitter_29)
        self.textBrowser_8 = QTextBrowser(self.splitter_28)
        self.textBrowser_8.setObjectName(u"textBrowser_8")
        self.splitter_28.addWidget(self.textBrowser_8)
        self.splitter_30 = QSplitter(self.scrollAreaWidgetContents_5)
        self.splitter_30.setObjectName(u"splitter_30")
        self.splitter_30.setGeometry(QRect(20, 10, 161, 71))
        self.splitter_30.setOrientation(Qt.Vertical)
        self.splitter_31 = QSplitter(self.splitter_30)
        self.splitter_31.setObjectName(u"splitter_31")
        self.splitter_31.setOrientation(Qt.Horizontal)
        self.label_45 = QLabel(self.splitter_31)
        self.label_45.setObjectName(u"label_45")
        self.splitter_31.addWidget(self.label_45)
        self.pushButton_12 = QPushButton(self.splitter_31)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_31.addWidget(self.pushButton_12)
        self.splitter_30.addWidget(self.splitter_31)
        self.textBrowser_9 = QTextBrowser(self.splitter_30)
        self.textBrowser_9.setObjectName(u"textBrowser_9")
        self.splitter_30.addWidget(self.textBrowser_9)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.pushButton_13 = QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(1510, 30, 21, 21))
        icon = QIcon()
        icon.addFile(u"../images.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setIconSize(QSize(25, 25))
        self.pushButton_13.setFlat(True)
        self.label_47 = QLabel(self.scrollAreaWidgetContents_3)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(540, 300, 22, 22))
        self.label_47.setFrameShape(QFrame.Panel)
        self.label_47.setFrameShadow(QFrame.Raised)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.upload_tab.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.upload_tab.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.upload_tab.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.upload_tab.addTab(self.tab_12, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1625, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.upload_tab.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Past Visit's", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Gynaac History", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Dignosis", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Chief Complaints", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Clear Complaints", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"WT", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"PR", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Temp", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Local Examination", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"SPO2", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"RR", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"BMI", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"HT", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"/min", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"CM", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"BP", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Kg", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"mmHg", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"/min", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"mmHg", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Examination", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"More Examinations", None))

        __sortingEnabled = self.tableComplaints.isSortingEnabled()
        self.tableComplaints.setSortingEnabled(False)
        ___qtablewidgetitem = self.tableComplaints.item(0, 0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Sr.No", None));
        ___qtablewidgetitem1 = self.tableComplaints.item(0, 1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Complaint Name", None));
        ___qtablewidgetitem2 = self.tableComplaints.item(0, 2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Duration", None));
        ___qtablewidgetitem3 = self.tableComplaints.item(0, 3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Word Not Visible", None));
        ___qtablewidgetitem4 = self.tableComplaints.item(0, 4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Clinical Note", None));
        ___qtablewidgetitem5 = self.tableComplaints.item(0, 5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Action", None));
        self.tableComplaints.setSortingEnabled(__sortingEnabled)

        self.label_42.setText(QCoreApplication.translate("MainWindow", u"History", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Quick History", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Personal", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Personal", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Personal", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.pushButton_13.setText("")
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"EMR & Prescription", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Certificates", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Refer", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Upload Images", None))
    # retranslateUi

