# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fgfdgfdgdahoxdC.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QGridLayout,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QScrollArea, QSizePolicy,
    QSplitter, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(906, 613)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 869, 533))
        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.widget = QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(u"widget")
        self.upload_tab = QTabWidget(self.widget)
        self.upload_tab.setObjectName(u"upload_tab")
        self.upload_tab.setGeometry(QRect(10, 20, 1321, 601))
        self.upload_tab.setFocusPolicy(Qt.TabFocus)
        self.upload_tab.setTabShape(QTabWidget.Rounded)
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.upload_tab.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.upload_tab.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.scrollArea_3 = QScrollArea(self.tab_9)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(-110, -50, 1521, 681))
        self.scrollArea_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setObjectName(u"scrollAreaWidgetContents_6")
        self.scrollAreaWidgetContents_6.setGeometry(QRect(0, 0, 1502, 662))
        self.label_46 = QLabel(self.scrollAreaWidgetContents_6)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(1270, 0, 49, 16))
        self.splitter_17 = QSplitter(self.scrollAreaWidgetContents_6)
        self.splitter_17.setObjectName(u"splitter_17")
        self.splitter_17.setGeometry(QRect(30, 0, 201, 24))
        self.splitter_17.setOrientation(Qt.Horizontal)
        self.label_47 = QLabel(self.splitter_17)
        self.label_47.setObjectName(u"label_47")
        self.splitter_17.addWidget(self.label_47)
        self.pushButton_13 = QPushButton(self.splitter_17)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.splitter_17.addWidget(self.pushButton_13)
        self.scrollArea_4 = QScrollArea(self.scrollAreaWidgetContents_6)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(590, 30, 351, 251))
        self.scrollArea_4.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_4.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 332, 232))
        self.layoutWidget = QWidget(self.scrollAreaWidgetContents_7)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 10, 423, 334))
        self.gridLayout_3 = QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_57 = QLabel(self.layoutWidget)
        self.label_57.setObjectName(u"label_57")

        self.gridLayout_3.addWidget(self.label_57, 0, 0, 1, 1)

        self.splitter_33 = QSplitter(self.layoutWidget)
        self.splitter_33.setObjectName(u"splitter_33")
        self.splitter_33.setOrientation(Qt.Horizontal)
        self.lineEdit_22 = QLineEdit(self.splitter_33)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.splitter_33.addWidget(self.lineEdit_22)
        self.label_60 = QLabel(self.splitter_33)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setFrameShape(QFrame.Panel)
        self.label_60.setFrameShadow(QFrame.Raised)
        self.splitter_33.addWidget(self.label_60)

        self.gridLayout_3.addWidget(self.splitter_33, 0, 1, 1, 1)

        self.label_50 = QLabel(self.layoutWidget)
        self.label_50.setObjectName(u"label_50")

        self.gridLayout_3.addWidget(self.label_50, 0, 2, 1, 1)

        self.splitter_34 = QSplitter(self.layoutWidget)
        self.splitter_34.setObjectName(u"splitter_34")
        self.splitter_34.setOrientation(Qt.Horizontal)
        self.lineEdit_23 = QLineEdit(self.splitter_34)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.splitter_34.addWidget(self.lineEdit_23)
        self.label_62 = QLabel(self.splitter_34)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setFrameShape(QFrame.Panel)
        self.label_62.setFrameShadow(QFrame.Raised)
        self.splitter_34.addWidget(self.label_62)

        self.gridLayout_3.addWidget(self.splitter_34, 0, 3, 2, 1)

        self.label_56 = QLabel(self.layoutWidget)
        self.label_56.setObjectName(u"label_56")

        self.gridLayout_3.addWidget(self.label_56, 1, 0, 2, 1)

        self.lineEdit_19 = QLineEdit(self.layoutWidget)
        self.lineEdit_19.setObjectName(u"lineEdit_19")

        self.gridLayout_3.addWidget(self.lineEdit_19, 1, 1, 2, 1)

        self.label_61 = QLabel(self.layoutWidget)
        self.label_61.setObjectName(u"label_61")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)

        self.gridLayout_3.addWidget(self.label_61, 2, 2, 1, 1)

        self.splitter_35 = QSplitter(self.layoutWidget)
        self.splitter_35.setObjectName(u"splitter_35")
        self.splitter_35.setOrientation(Qt.Horizontal)
        self.lineEdit_24 = QLineEdit(self.splitter_35)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.splitter_35.addWidget(self.lineEdit_24)
        self.label_63 = QLabel(self.splitter_35)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setFrameShape(QFrame.Panel)
        self.label_63.setFrameShadow(QFrame.Raised)
        self.splitter_35.addWidget(self.label_63)

        self.gridLayout_3.addWidget(self.splitter_35, 2, 3, 2, 1)

        self.label_55 = QLabel(self.layoutWidget)
        self.label_55.setObjectName(u"label_55")

        self.gridLayout_3.addWidget(self.label_55, 3, 0, 2, 1)

        self.splitter_32 = QSplitter(self.layoutWidget)
        self.splitter_32.setObjectName(u"splitter_32")
        self.splitter_32.setOrientation(Qt.Horizontal)
        self.lineEdit_21 = QLineEdit(self.splitter_32)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.splitter_32.addWidget(self.lineEdit_21)
        self.label_59 = QLabel(self.splitter_32)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setFrameShape(QFrame.Panel)
        self.label_59.setFrameShadow(QFrame.Raised)
        self.splitter_32.addWidget(self.label_59)

        self.gridLayout_3.addWidget(self.splitter_32, 3, 1, 2, 1)

        self.label_51 = QLabel(self.layoutWidget)
        self.label_51.setObjectName(u"label_51")
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)

        self.gridLayout_3.addWidget(self.label_51, 4, 2, 1, 1)

        self.splitter_36 = QSplitter(self.layoutWidget)
        self.splitter_36.setObjectName(u"splitter_36")
        self.splitter_36.setOrientation(Qt.Horizontal)
        self.lineEdit_25 = QLineEdit(self.splitter_36)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.splitter_36.addWidget(self.lineEdit_25)
        self.label_64 = QLabel(self.splitter_36)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setFrameShape(QFrame.Panel)
        self.label_64.setFrameShadow(QFrame.Raised)
        self.splitter_36.addWidget(self.label_64)

        self.gridLayout_3.addWidget(self.splitter_36, 4, 3, 2, 1)

        self.label_54 = QLabel(self.layoutWidget)
        self.label_54.setObjectName(u"label_54")

        self.gridLayout_3.addWidget(self.label_54, 5, 0, 2, 1)

        self.splitter_25 = QSplitter(self.layoutWidget)
        self.splitter_25.setObjectName(u"splitter_25")
        self.splitter_25.setOrientation(Qt.Horizontal)
        self.lineEdit_20 = QLineEdit(self.splitter_25)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.splitter_25.addWidget(self.lineEdit_20)
        self.label_58 = QLabel(self.splitter_25)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setFrameShape(QFrame.Panel)
        self.label_58.setFrameShadow(QFrame.Raised)
        self.splitter_25.addWidget(self.label_58)

        self.gridLayout_3.addWidget(self.splitter_25, 5, 1, 2, 1)

        self.label_52 = QLabel(self.layoutWidget)
        self.label_52.setObjectName(u"label_52")

        self.gridLayout_3.addWidget(self.label_52, 6, 2, 1, 1)

        self.splitter_37 = QSplitter(self.layoutWidget)
        self.splitter_37.setObjectName(u"splitter_37")
        self.splitter_37.setOrientation(Qt.Horizontal)
        self.lineEdit_26 = QLineEdit(self.splitter_37)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.splitter_37.addWidget(self.lineEdit_26)
        self.label_65 = QLabel(self.splitter_37)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setFrameShape(QFrame.Panel)
        self.label_65.setFrameShadow(QFrame.Raised)
        self.splitter_37.addWidget(self.label_65)

        self.gridLayout_3.addWidget(self.splitter_37, 6, 3, 1, 1)

        self.label_53 = QLabel(self.layoutWidget)
        self.label_53.setObjectName(u"label_53")

        self.gridLayout_3.addWidget(self.label_53, 7, 0, 1, 2)

        self.textBrowser_10 = QTextBrowser(self.layoutWidget)
        self.textBrowser_10.setObjectName(u"textBrowser_10")

        self.gridLayout_3.addWidget(self.textBrowser_10, 8, 0, 1, 4)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_7)
        self.splitter_38 = QSplitter(self.scrollAreaWidgetContents_6)
        self.splitter_38.setObjectName(u"splitter_38")
        self.splitter_38.setGeometry(QRect(590, 0, 191, 24))
        self.splitter_38.setOrientation(Qt.Horizontal)
        self.label_66 = QLabel(self.splitter_38)
        self.label_66.setObjectName(u"label_66")
        self.splitter_38.addWidget(self.label_66)
        self.pushButton_15 = QPushButton(self.splitter_38)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.splitter_38.addWidget(self.pushButton_15)
        self.splitter_39 = QSplitter(self.scrollAreaWidgetContents_6)
        self.splitter_39.setObjectName(u"splitter_39")
        self.splitter_39.setGeometry(QRect(1000, 0, 191, 24))
        self.splitter_39.setOrientation(Qt.Horizontal)
        self.label_67 = QLabel(self.splitter_39)
        self.label_67.setObjectName(u"label_67")
        self.splitter_39.addWidget(self.label_67)
        self.pushButton_16 = QPushButton(self.splitter_39)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.splitter_39.addWidget(self.pushButton_16)
        self.scrollArea_5 = QScrollArea(self.scrollAreaWidgetContents_6)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setGeometry(QRect(1000, 30, 211, 261))
        self.scrollArea_5.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_5.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea_5.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_8 = QWidget()
        self.scrollAreaWidgetContents_8.setObjectName(u"scrollAreaWidgetContents_8")
        self.scrollAreaWidgetContents_8.setGeometry(QRect(0, 0, 192, 242))
        self.splitter_40 = QSplitter(self.scrollAreaWidgetContents_8)
        self.splitter_40.setObjectName(u"splitter_40")
        self.splitter_40.setGeometry(QRect(20, 90, 161, 71))
        self.splitter_40.setOrientation(Qt.Vertical)
        self.splitter_41 = QSplitter(self.splitter_40)
        self.splitter_41.setObjectName(u"splitter_41")
        self.splitter_41.setOrientation(Qt.Horizontal)
        self.label_68 = QLabel(self.splitter_41)
        self.label_68.setObjectName(u"label_68")
        self.splitter_41.addWidget(self.label_68)
        self.pushButton_17 = QPushButton(self.splitter_41)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.splitter_41.addWidget(self.pushButton_17)
        self.splitter_40.addWidget(self.splitter_41)
        self.textBrowser_11 = QTextBrowser(self.splitter_40)
        self.textBrowser_11.setObjectName(u"textBrowser_11")
        self.splitter_40.addWidget(self.textBrowser_11)
        self.splitter_42 = QSplitter(self.scrollAreaWidgetContents_8)
        self.splitter_42.setObjectName(u"splitter_42")
        self.splitter_42.setGeometry(QRect(20, 170, 161, 71))
        self.splitter_42.setOrientation(Qt.Vertical)
        self.splitter_43 = QSplitter(self.splitter_42)
        self.splitter_43.setObjectName(u"splitter_43")
        self.splitter_43.setOrientation(Qt.Horizontal)
        self.label_69 = QLabel(self.splitter_43)
        self.label_69.setObjectName(u"label_69")
        self.splitter_43.addWidget(self.label_69)
        self.pushButton_18 = QPushButton(self.splitter_43)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.splitter_43.addWidget(self.pushButton_18)
        self.splitter_42.addWidget(self.splitter_43)
        self.textBrowser_12 = QTextBrowser(self.splitter_42)
        self.textBrowser_12.setObjectName(u"textBrowser_12")
        self.splitter_42.addWidget(self.textBrowser_12)
        self.splitter_44 = QSplitter(self.scrollAreaWidgetContents_8)
        self.splitter_44.setObjectName(u"splitter_44")
        self.splitter_44.setGeometry(QRect(20, 10, 161, 71))
        self.splitter_44.setOrientation(Qt.Vertical)
        self.splitter_45 = QSplitter(self.splitter_44)
        self.splitter_45.setObjectName(u"splitter_45")
        self.splitter_45.setOrientation(Qt.Horizontal)
        self.label_70 = QLabel(self.splitter_45)
        self.label_70.setObjectName(u"label_70")
        self.splitter_45.addWidget(self.label_70)
        self.pushButton_19 = QPushButton(self.splitter_45)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.splitter_45.addWidget(self.pushButton_19)
        self.splitter_44.addWidget(self.splitter_45)
        self.textBrowser_13 = QTextBrowser(self.splitter_44)
        self.textBrowser_13.setObjectName(u"textBrowser_13")
        self.splitter_44.addWidget(self.textBrowser_13)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_8)
        self.tableComplaint = QTableWidget(self.scrollAreaWidgetContents_6)
        if (self.tableComplaint.columnCount() < 5):
            self.tableComplaint.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableComplaint.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableComplaint.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableComplaint.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableComplaint.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableComplaint.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableComplaint.setObjectName(u"tableComplaint")
        self.tableComplaint.setGeometry(QRect(30, 50, 501, 161))
        self.tableComplaint.setFrameShape(QFrame.Box)
        self.tableComplaint.setAlternatingRowColors(True)
        self.tableComplaint.setIconSize(QSize(0, 0))
        self.tableComplaint.setGridStyle(Qt.SolidLine)
        self.tableComplaint.setSortingEnabled(False)
        self.tableComplaint.verticalHeader().setVisible(True)
        self.tableComplaint.verticalHeader().setCascadingSectionResizes(True)
        self.tableComplaint.verticalHeader().setProperty("showSortIndicator", True)
        self.label_71 = QLabel(self.scrollAreaWidgetContents_6)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(28, 250, 91, 20))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_71.setFont(font)
        self.pushButton_21 = QPushButton(self.scrollAreaWidgetContents_6)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(130, 250, 102, 24))
        self.pushButton_21.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.pushButton_22 = QPushButton(self.scrollAreaWidgetContents_6)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(240, 250, 141, 24))
        self.pushButton_22.setStyleSheet(u"background-color: rgb(255, 85, 0);")
        self.pushButton_23 = QPushButton(self.scrollAreaWidgetContents_6)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(390, 250, 102, 24))
        self.pushButton_23.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.tableWidget_2 = QTableWidget(self.scrollAreaWidgetContents_6)
        if (self.tableWidget_2.columnCount() < 9):
            self.tableWidget_2.setColumnCount(9)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        icon = QIcon()
        icon.addFile(u"settings-icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setIcon(icon);
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, __qtablewidgetitem13)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(30, 300, 1421, 331))
        self.tableWidget_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableWidget_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableWidget_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.splitter_46 = QSplitter(self.scrollAreaWidgetContents_6)
        self.splitter_46.setObjectName(u"splitter_46")
        self.splitter_46.setGeometry(QRect(1260, 30, 161, 21))
        self.splitter_46.setOrientation(Qt.Horizontal)
        self.label_49 = QLabel(self.splitter_46)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setFrameShape(QFrame.Panel)
        self.label_49.setFrameShadow(QFrame.Raised)
        self.splitter_46.addWidget(self.label_49)
        self.lineEdit_18 = QLineEdit(self.splitter_46)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.splitter_46.addWidget(self.lineEdit_18)
        self.pushButton_20 = QPushButton(self.splitter_46)
        self.pushButton_20.setObjectName(u"pushButton_20")
        icon1 = QIcon()
        icon1.addFile(u"../images.jpg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setIconSize(QSize(25, 25))
        self.pushButton_20.setFlat(True)
        self.splitter_46.addWidget(self.pushButton_20)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_6)
        self.upload_tab.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.upload_tab.addTab(self.tab_10, "")
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.upload_tab.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.upload_tab.addTab(self.tab_12, "")

        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 906, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.upload_tab.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Past Visit's", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Gynaac History", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Dignosis", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Chief Complaints", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Clear Complaints", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"HT", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"CM", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"WT", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"Kg", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"BMI", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"BP", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"mmHg", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"RR", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"/min", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"PR", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"/min", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"SPO2", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Temp", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"mmHg", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Local Examination", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Examination", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"More Examinations", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"History", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Quick History", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Personal", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"Personal", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"Personal", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        ___qtablewidgetitem = self.tableComplaint.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Complaint Name", None));
        ___qtablewidgetitem1 = self.tableComplaint.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Duration", None));
        ___qtablewidgetitem2 = self.tableComplaint.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Word Not Visible", None));
        ___qtablewidgetitem3 = self.tableComplaint.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Clinical", None));
        ___qtablewidgetitem4 = self.tableComplaint.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Action", None));
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Prescription", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"Clear Prescription", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"Delete Multiple Medicins", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"Review History", None))
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Select", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"New Column", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Medicine Name", None));
        ___qtablewidgetitem8 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Generic Name", None));
        ___qtablewidgetitem9 = self.tableWidget_2.horizontalHeaderItem(4)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Qty", None));
        ___qtablewidgetitem10 = self.tableWidget_2.horizontalHeaderItem(5)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Frequency", None));
        ___qtablewidgetitem11 = self.tableWidget_2.horizontalHeaderItem(6)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Days", None));
        ___qtablewidgetitem12 = self.tableWidget_2.horizontalHeaderItem(7)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Instruction", None));
        ___qtablewidgetitem13 = self.tableWidget_2.horizontalHeaderItem(8)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Action", None));
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.pushButton_20.setText("")
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"EMR & Prescription", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Certificates", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Refer", None))
        self.upload_tab.setTabText(self.upload_tab.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Upload Images", None))
    # retranslateUi

